baseURL = 'https://lucatung.me/'
locale = 'en-us'
title = "Luca Tung's Weblog"
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[params]
  math = true

  mainSections = ["posts"]

  [params.homeInfoParams]
    Title = "Hi folks!"
    Content = "I'm a software engineer with 9 years of experience. I use this space to share my passion for software engineering, computer vision, and numerical algorithms."

  [[params.socialIcons]]
      name = "github"
      url = "https://github.com/lucatung"

    [[params.socialIcons]]
      name = "X"
      url = "https://x.com/lucatungtech"

    [[params.socialIcons]]
      name = "email"
      url = "mailto:askluca94@gmail.com"
