baseURL = 'https://lucatung.me/'
locale = 'en-us'
title = "Luca's Weblog"
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[params]
  math = true
