baseURL = 'https://lucatung.me/'
locale = 'en-us'
title = "Luca Tung's Weblog"
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[params]
  math = true

  mainSections = ["posts"]

  [params.homeInfoParams]
    Title = "Hi, this is Luca Tung's Weblog!"
    Content = "Notes on software engineering, computer vision, numerical algorithms, etc."

  [[params.socialIcons]]
      name = "github"
      url = "https://github.com/lucatung"

    [[params.socialIcons]]
      name = "X"
      url = "https://x.com/lucatungtech"

    [[params.socialIcons]]
      name = "email"
      url = "mailto:askluca94@gmail.com"
